### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by reeddeer** [SuperTux/flexlay#80]
Hi @SuperTux

The title says most of it, but there are a few things that I would like to add on

1. Why haven't there been any changes recently?
2. If this project is inactive(which it appears to be), where can I get something like it?
3. What happened to the old supertux editor?
4. The question in the title

Thanks,
Reed Kemp

**Comment by reeddeer** [comment]
That was what I was about to do
😄

**Comment by maxteufel** [comment]
> 1. Why haven't there been any changes recently?

There was the idea to rewrite this entire thing for performance reasons, but that idea got dropped mostly (Cc: @Karkus476). Now, once time allows, @Karkus476 wanted to work on improving performance anyway (mostly related to redrawing tiles), if I remember correctly. However, we don't have unlimited time to do so and developing the main game is relatively time consuming as well. Also, this works a bit, and for official purposes using either the Mono/C# level editor or the in-game editor is recommended. Our current level designers tend to use the in-game one right now, so there's little use to changing something.

> 2. If this project is inactive(which it appears to be), where can I get something like it?

It's definitely not a dead project, but probably currently not developed. However if you report any high-severity issues, we might work on them. If you want to contribute on it, you're welcome to do so! You can get something similar in the old level editor or the in-game editor.

> 3. What happened to the old supertux editor?

It's dead. That means we will not change it anymore, even when there are issues. There is the in-game level editor which you can use, or if you need something separate you can use flexlay (but be aware that flexlay is not stable yet and might contain issues - however if you report them we'll try to fix them).

> 4. The question in the title

See answer 2. It's not dead, but also hasn't the highest priority.

If this is enough explication, please close the issue, otherwise ask for more information!

**Comment by maxteufel** [comment]
@reeddeer Also, please avoid mentioning random people here. They get emails for comments, as do people listed in <https://github.com/SuperTux/flexlay/watchers>.

**Comment by reeddeer** [comment]
Ok, @maxteufel I will remove them

**Comment by reeddeer** [comment]
@maxteufel Thank you very much! 😃 This is just what I asked for!
From,
Reed Kemp
