### ISSUE TITLE
Background Images Don't Show in Editor

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/flexlay#9]
Title says it all

**Comment by Karkus476** [comment]
I'm beginning to wonder if they should... after all they are supposed to move along with the player, which we cannot emulate. What do you think @tobbi

**Comment by tobbi** [comment]
How does the old editor handle this, currently? I am inclined to let them scroll together with the scrolling of the user so that the background image is always displayed at 0'0, no matter where we scroll inside the editor...Am I making any sense here? On the other hand, if the user zooms out... Are the images tileable, could we simply append them?

**Comment by Karkus476** [comment]
![screenshot from 2015-12-03 16 49 42](https://cloud.githubusercontent.com/assets/14023329/11567237/fb18ffce-99dd-11e5-9f12-62632f4a59a4.png) not great, to be honest. Your idea is good, but anything is going to look dodgy because in supertux there isn't any zooming out. No, they aren't really tileable

**Comment by Karkus476** [comment]
I'm not going to add this, as the way background images are rendered in the game doesn't work for the editor
